spring:
  application:
    name: loan-application
  datasource:
    url: jdbc:postgresql://localhost:5432/operaton
    username: operaton
    password: operaton
  mail:
    host: localhost
    port: 1025

credit:
  score:
    service:
      url: http://localhost:8080

operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    filter:
      create: All tasks
