# Datasource — Quarkus/Agroal
quarkus.datasource.operaton-db.db-kind=postgresql
quarkus.datasource.operaton-db.jdbc.url=jdbc:postgresql://localhost:5432/operaton
quarkus.datasource.operaton-db.username=operaton
quarkus.datasource.operaton-db.password=operaton

# Operaton engine uses the named datasource
quarkus.operaton.datasource=operaton-db
quarkus.operaton.generic-config.history=full
quarkus.operaton.generic-config.history-time-to-live=P30D
quarkus.operaton.generic-config.database-schema-update=true

# HTTP port
quarkus.http.port=8080
