spring:
  application:
    name: process-migration
  datasource:
    url: jdbc:postgresql://localhost:5432/operaton
    username: operaton
    password: operaton
    driver-class-name: org.postgresql.Driver

operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    history-level: full
    auto-deployment-enabled: false
