spring:
  application:
    name: integration-mail
  datasource:
    url: jdbc:postgresql://localhost:5432/operaton
    username: operaton
    password: operaton
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    filter:
      create: All tasks
