spring:
  application:
    name: integration-kafka
  datasource:
    url: jdbc:postgresql://localhost:5432/operaton
    username: operaton
    password: operaton
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: operaton-examples
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
kafka:
  topics:
    orders: orders
    results: order-results
operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    filter:
      create: All tasks
