spring:
  application:
    name: timer-events
  datasource:
    url: jdbc:postgresql://localhost:5432/operaton
    username: operaton
    password: operaton
operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    filter:
      create: All tasks
